<?php

namespace ContainerLU6x9S5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SFD3KwvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sFD3Kwv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sFD3Kwv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\MessageController::delete' => ['privates', '.service_locator.R7OaP6G', 'get_ServiceLocator_R7OaP6GService', true],
            'App\\Controller\\MessageController::edit' => ['privates', '.service_locator.R7OaP6G', 'get_ServiceLocator_R7OaP6GService', true],
            'App\\Controller\\MessageController::index' => ['privates', '.service_locator.tQUwO87', 'get_ServiceLocator_TQUwO87Service', true],
            'App\\Controller\\MessageController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MessageController::show' => ['privates', '.service_locator.MjFFzS6', 'get_ServiceLocator_MjFFzS6Service', true],
            'App\\Controller\\MessagerieController::index' => ['privates', '.service_locator.5XW3WAE', 'get_ServiceLocator_5XW3WAEService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\MessageController:delete' => ['privates', '.service_locator.R7OaP6G', 'get_ServiceLocator_R7OaP6GService', true],
            'App\\Controller\\MessageController:edit' => ['privates', '.service_locator.R7OaP6G', 'get_ServiceLocator_R7OaP6GService', true],
            'App\\Controller\\MessageController:index' => ['privates', '.service_locator.tQUwO87', 'get_ServiceLocator_TQUwO87Service', true],
            'App\\Controller\\MessageController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\MessageController:show' => ['privates', '.service_locator.MjFFzS6', 'get_ServiceLocator_MjFFzS6Service', true],
            'App\\Controller\\MessagerieController:index' => ['privates', '.service_locator.5XW3WAE', 'get_ServiceLocator_5XW3WAEService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\MessageController::delete' => '?',
            'App\\Controller\\MessageController::edit' => '?',
            'App\\Controller\\MessageController::index' => '?',
            'App\\Controller\\MessageController::new' => '?',
            'App\\Controller\\MessageController::show' => '?',
            'App\\Controller\\MessagerieController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MessageController:delete' => '?',
            'App\\Controller\\MessageController:edit' => '?',
            'App\\Controller\\MessageController:index' => '?',
            'App\\Controller\\MessageController:new' => '?',
            'App\\Controller\\MessageController:show' => '?',
            'App\\Controller\\MessagerieController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
