<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLU6x9S5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLU6x9S5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLU6x9S5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLU6x9S5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLU6x9S5\App_KernelDevDebugContainer([
    'container.build_hash' => 'LU6x9S5',
    'container.build_id' => 'eb26f1db',
    'container.build_time' => 1752665525,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLU6x9S5');
